[package]
name = "competitive_rust_libraries"
version = "0.1.0"
authors = ["htlsne <htlsne23@gmail.com>"]
edition = "2018"

[dependencies]
ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }
maplit = "1.0.2"
proconio = "0.4.1"
